// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKo8MMMrHbMgvDnsAB719-XD4GbkIzDpI',
    appId: '1:100729417136:web:dd07aac3ed2253b0da3a75',
    messagingSenderId: '100729417136',
    projectId: 'helpdoc-a0945',
    authDomain: 'helpdoc-a0945.firebaseapp.com',
    storageBucket: 'helpdoc-a0945.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsrik9RCNB2Fgs8HT81-R5BgxslRsUvGs',
    appId: '1:100729417136:android:9b2c3a920e8de5fbda3a75',
    messagingSenderId: '100729417136',
    projectId: 'helpdoc-a0945',
    storageBucket: 'helpdoc-a0945.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4fr_FcyzWG96FZCuxCEFiCaq7PGJQUN8',
    appId: '1:100729417136:ios:5b347d7b3207c735da3a75',
    messagingSenderId: '100729417136',
    projectId: 'helpdoc-a0945',
    storageBucket: 'helpdoc-a0945.appspot.com',
    iosClientId: '100729417136-65fhu138n01un3aj09aaijhib5q7kk3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorHelpApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4fr_FcyzWG96FZCuxCEFiCaq7PGJQUN8',
    appId: '1:100729417136:ios:6a34e03f6c28ff65da3a75',
    messagingSenderId: '100729417136',
    projectId: 'helpdoc-a0945',
    storageBucket: 'helpdoc-a0945.appspot.com',
    iosClientId: '100729417136-fvt25hpk0b73i28851c93kali4nfrk21.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorHelpApp.RunnerTests',
  );
}
